using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TimetableDownloader
{
    class MetroTouchingGenerator : ITouchingSource
    {
        public List<LocationPair> getTouchingLocations(Dictionary<string, int> items)
        {
            List<LocationPair> l = new List<LocationPair>();
            l.Add(getTL("Ballyduff, Doagh Road", "Ballyduff, Forthill Drive", items));
            l.Add(getTL("Ballyduff, Forthill Drive", "Fairview Rd, Beverley Shops", items));
            l.Add(getTL("Fairview Rd, Beverley Shops", "Carnmoney, Carnvue", items));
            l.Add(getTL("Carnmoney, Carnvue", "Carnmoney, Burnthill Road", items));
            l.Add(getTL("Carnmoney, Burnthill Road", "Glengormley, Centre", items));
            l.Add(getTL("Glengormley, Centre", "Antrim Road, Bellevue", items));
            l.Add(getTL("Antrim Road, Bellevue", "Antrim Road, Serpentine Road", items));
            l.Add(getTL("Antrim Road, Serpentine Road", "Antrim Road, Salisbury Ave", items));
            l.Add(getTL("Antrim Road, Salisbury Ave", "Antrim Road, Atlantic Avenue", items));
            l.Add(getTL("Antrim Road, Atlantic Avenue", "Carlisle Circus, Antrim Road", items));
            l.Add(getTL("Carlisle Circus, Antrim Road", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("Glenville, Monkstown Avenue", "Ballyduff, Doagh Road", items));
            l.Add(getTL("Belfast, Upper Queen Street", "Carlisle Circus, Antrim Road", items));
            l.Add(getTL("Carlisle Circus, Antrim Road", "Antrim Road, Eia Street", items));
            l.Add(getTL("Antrim Road, Eia Street", "Antrim Road, Salisbury Ave", items));
            l.Add(getTL("New Mossley, Manse Way", "Ballyhenry, Ballyearl Way", items));
            l.Add(getTL("Ballyhenry, Ballyearl Way", "Glengormley, Northcott Link Road", items));
            l.Add(getTL("Glengormley, Northcott Link Road", "Antrim Road, Burney's Lane", items));
            l.Add(getTL("Antrim Road, Burney's Lane", "Glengormley, Centre", items));
            l.Add(getTL("Fairview Rd, Beverley Shops", "Ballyhenry, Ballyearl Way", items));
            l.Add(getTL("Mossley, Glade", "Ballyhenry, Ballyearl Way", items));
            l.Add(getTL("Ballyhenry, Ballyearl Way", "Ballyclare Road, Northcott", items));
            l.Add(getTL("Ballyclare Road, Northcott", "Glengormley, Centre", items));
            l.Add(getTL("Antrim Road, Atlantic Avenue", "Yorkgate, North Queen Street", items));
            l.Add(getTL("Yorkgate, North Queen Street", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("Belfast, Upper Queen Street", "Yorkgate, North Queen Street", items));
            l.Add(getTL("Yorkgate, North Queen Street", "Antrim Road, Eia Street", items));
            l.Add(getTL("Roughfort, Turning Circle", "Mallusk, Parkmount", items));
            l.Add(getTL("Mallusk, Parkmount", "Mallusk Road, Ballyrobert Garage", items));
            l.Add(getTL("Mallusk Road, Ballyrobert Garage", "Hightown Road, Turning Circle", items));
            l.Add(getTL("Hightown Road, Turning Circle", "Glengormley, Centre", items));
            l.Add(getTL("Antrim Road, Burney's Lane", "Sandyknowles Roundabout, Roundabout", items));
            l.Add(getTL("Sandyknowles Roundabout, Roundabout", "Blackrock, Square", items));
            l.Add(getTL("Ballyhenry, Ballyearl Way", "Sandyknowes, Ballyhenry Road", items));
            l.Add(getTL("Sandyknowes, Ballyhenry Road", "Sandyknowles Roundabout, Roundabout", items));
            l.Add(getTL("Royal Mail, Enterprise Way", "Hightown Road, Turning Circle", items));
            l.Add(getTL("Antrim Road, Bellevue", "Upper Whitewell, Throne Centre", items));
            l.Add(getTL("Upper Whitewell, Throne Centre", "Lower Whitewell, White City", items));
            l.Add(getTL("Lower Whitewell, White City", "Shore Road, Gray's La", items));
            l.Add(getTL("Shore Road, Gray's La", "Shore Road, Lidl/Asda", items));
            l.Add(getTL("Shore Road, Lidl/Asda", "Yorkgate, Station (bus)", items));
            l.Add(getTL("Yorkgate, Station (bus)", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("Fairview Rd, Turning Circle", "Fairview Rd, Beverley Shops", items));
            l.Add(getTL("Belfast, Upper Queen Street", "Yorkgate, Station (bus)", items));
            l.Add(getTL("Fairview Rd, Beverley Shops", "Ballyclare Road, Northcott", items));
            l.Add(getTL("Upper Whitewell, Throne Centre", "Abbeycentre, Longwood Road", items));
            l.Add(getTL("Abbeycentre, Longwood Road", "Shore Road, Gray's La", items));
            l.Add(getTL("Monkstown, Devenish Drive", "Doagh Road, Cherrylands", items));
            l.Add(getTL("Doagh Road, Cherrylands", "Cloughfern, Whiteabbey Hospl", items));
            l.Add(getTL("Cloughfern, Whiteabbey Hospl", "Doagh Road, Green End", items));
            l.Add(getTL("Doagh Road, Green End", "Merville Garden Village, Garden Village", items));
            l.Add(getTL("Merville Garden Village, Garden Village", "Shore Road, Gray's La", items));
            l.Add(getTL("Doagh Road, Green End", "Rathcoole, Primary School", items));
            l.Add(getTL("Rathcoole, Primary School", "Valley Leisure Cen, Bus stop", items));
            l.Add(getTL("Valley Leisure Cen, Bus stop", "Church Road, Tesco", items));
            l.Add(getTL("Church Road, Tesco", "Abbeycentre, Longwood Road", items));
            l.Add(getTL("Rathcoole, Primary School", "Rathcoole, Diamond", items));
            l.Add(getTL("Rathcoole, Diamond", "Merville Garden Village, Garden Village", items));
            l.Add(getTL("Belfast, Donegall Sq West", "Belfast, Queens Square Albert Clock", items));
            l.Add(getTL("Belfast, Queens Square Albert Clock", "Short Strand, Newtownards Rd", items));
            l.Add(getTL("Short Strand, Newtownards Rd", "Connswater, Newtownards Rd", items));
            l.Add(getTL("Connswater, Newtownards Rd", "Connsbrook Avenue, Larkfield", items));
            l.Add(getTL("Connsbrook Avenue, Larkfield", "Sydenham, Station", items));
            l.Add(getTL("Sydenham, Station", "Holywood Rd, Tillysburn Park", items));
            l.Add(getTL("Holywood Rd, Tillysburn Park", "Knocknagoney, Tesco", items));
            l.Add(getTL("Knocknagoney, Tesco", "Holywood Rd, Knocknagoney Ave", items));
            l.Add(getTL("Short Strand, Newtownards Rd", "Belfast, Donegall Sq West", items));
            l.Add(getTL("Ballybeen, Enler Centre", "Ballybeen, Culross Drive", items));
            l.Add(getTL("Ballybeen, Culross Drive", "Ballybeen, Rank Road", items));
            l.Add(getTL("Ballybeen, Rank Road", "Dundonald, Ulster Hospital", items));
            l.Add(getTL("Dundonald, Ulster Hospital", "Upper Newtownards Rd, Rosepark", items));
            l.Add(getTL("Upper Newtownards Rd, Rosepark", "Upper Newtownards Rd, Knock Road", items));
            l.Add(getTL("Upper Newtownards Rd, Knock Road", "Ballyhackamore, Village", items));
            l.Add(getTL("Ballyhackamore, Village", "Connswater, Newtownards Rd", items));
            l.Add(getTL("Connswater, Newtownards Rd", "Short Strand, Albertbridge Rd", items));
            l.Add(getTL("Short Strand, Albertbridge Rd", "Belfast, East Bridge St Central Stn", items));
            l.Add(getTL("Belfast, East Bridge St Central Stn", "Belfast, Donegall Sq West", items));
            l.Add(getTL("Dundonald, Ulster Hospital", "Ballybeen, Enler Centre", items));
            l.Add(getTL("Belfast, Queens Square Albert Clock", "Belfast, East Bridge St Central Stn", items));
            l.Add(getTL("Dundonald, Ulster Hospital", "Dundonald, Ulster Hospital", items));
            l.Add(getTL("Braniel, Farmhurst Green", "Whincroft Road, Bus stop", items));
            l.Add(getTL("Whincroft Road, Bus stop", "Castlereagh Rd, Clonduff", items));
            l.Add(getTL("Castlereagh Rd, Clonduff", "Castlereagh Rd, Ladas Drive", items));
            l.Add(getTL("Castlereagh Rd, Ladas Drive", "Short Strand, Mountpottinger Link", items));
            l.Add(getTL("Short Strand, Mountpottinger Link", "Belfast, City Hall", items));
            l.Add(getTL("Belfast, Queens Square Albert Clock", "Short Strand, Mountpottinger Link", items));
            l.Add(getTL("Castlereagh Rd, Clonduff", "Bloomfield Road, Roundabout", items));
            l.Add(getTL("Bloomfield Road, Roundabout", "Short Strand, Mountpottinger Link", items));
            l.Add(getTL("Belfast, Chichester Street", "Belfast, Queens Square Albert Clock", items));
            l.Add(getTL("Short Strand, Albertbridge Rd", "Cregagh Road, Bell's Bridge", items));
            l.Add(getTL("Cregagh Road, Bell's Bridge", "Cregagh Park, Bus stop", items));
            l.Add(getTL("Cregagh Park, Bus stop", "Forestside, Upper Galwally", items));
            l.Add(getTL("Belfast, East Bridge St Central Stn", "Belfast, City Hall", items));
            l.Add(getTL("Four Winds, Ballymaconaghy Rd", "Cairnshill Road, Cairnshill Court", items));
            l.Add(getTL("Cairnshill Road, Cairnshill Court", "Saintfield Rd, Glenhugh Park", items));
            l.Add(getTL("Saintfield Rd, Glenhugh Park", "Saintfield Rd, Mount Oriel", items));
            l.Add(getTL("Saintfield Rd, Mount Oriel", "Forestside, Knockbreda Cemy", items));
            l.Add(getTL("Forestside, Knockbreda Cemy", "Rosetta, St John's Church", items));
            l.Add(getTL("Rosetta, St John's Church", "Ormeau Road, Agincourt Avenue", items));
            l.Add(getTL("Ormeau Road, Agincourt Avenue", "Belfast, College Green", items));
            l.Add(getTL("Belfast, College Green", "Belfast, City Hall", items));
            l.Add(getTL("Saintfield Rd, Mount Oriel", "Forestside, Upper Galwally", items));
            l.Add(getTL("Forestside, Upper Galwally", "Rosetta, St John's Church", items));
            l.Add(getTL("Laurelgrove, Ballymaconaghy Road", "Four Winds, Ballymaconaghy Rd", items));
            l.Add(getTL("Belfast, Howard Street", "Belfast, College Green", items));
            l.Add(getTL("Rosetta, St John's Church", "Forestside, Saintfield Rd", items));
            l.Add(getTL("Forestside, Saintfield Rd", "Saintfield Rd, Mount Oriel", items));
            l.Add(getTL("Four Winds, Ballymaconaghy Rd", "Newton Park, Colby Park", items));
            l.Add(getTL("Newton Park, Colby Park", "Saintfield Rd, Mount Oriel", items));
            l.Add(getTL("Forestside, Knockbreda Cemy", "Mount Merrion, Rosetta Rd", items));
            l.Add(getTL("Mount Merrion, Rosetta Rd", "Rosetta, St John's Church", items));
            l.Add(getTL("Forestside, Upper Galwally", "Mount Merrion, Rosetta Rd", items));
            l.Add(getTL("Ormeau Road, Agincourt Avenue", "Rosetta, Knockbreda Road", items));
            l.Add(getTL("Rosetta, Knockbreda Road", "Mount Merrion, Rosetta Rd", items));
            l.Add(getTL("Malone, Erinvale Avenue", "Finaghy Rd Sth, Trossachs Dr", items));
            l.Add(getTL("Finaghy Rd Sth, Trossachs Dr", "Upper Malone Road, Dub Lane", items));
            l.Add(getTL("Upper Malone Road, Dub Lane", "Stranmillis, Broomhill Park", items));
            l.Add(getTL("Stranmillis, Broomhill Park", "Stranmillis, College", items));
            l.Add(getTL("Stranmillis, College", "Queens University, Elmwood Ave", items));
            l.Add(getTL("Queens University, Elmwood Ave", "Bradbury Place, Bus stop", items));
            l.Add(getTL("Bradbury Place, Bus stop", "Belfast, Great Northern Mall", items));
            l.Add(getTL("Belfast, Great Northern Mall", "Belfast, Wellington Place", items));
            l.Add(getTL("Belfast, Donegall Sq East", "Belfast, Great Northern Mall", items));
            l.Add(getTL("Upper Malone Road, Dub Lane", "Malone Road, Cranmore Park", items));
            l.Add(getTL("Malone Road, Cranmore Park", "Queens University, Elmwood Ave", items));
            l.Add(getTL("Ladybrook, Turning Circle", "Finaghy Rd Nth, Orchardville", items));
            l.Add(getTL("Finaghy Rd Nth, Orchardville", "Finaghy Rd Sth, Health Centre", items));
            l.Add(getTL("Finaghy Rd Sth, Health Centre", "Finaghy Rd Sth, Trossachs Dr", items));
            l.Add(getTL("Conway, River Road", "Seymour Hill, Estate Entrance", items));
            l.Add(getTL("Seymour Hill, Estate Entrance", "Dunmurry, Village", items));
            l.Add(getTL("Dunmurry, Village", "Finaghy, Crossroads Lisburn Rd", items));
            l.Add(getTL("Finaghy, Crossroads Lisburn Rd", "Lisburn Rd, Kings Hall", items));
            l.Add(getTL("Lisburn Rd, Kings Hall", "Lisburn Rd, Marlborough Pk", items));
            l.Add(getTL("Lisburn Rd, Marlborough Pk", "Lisburn Rd, City Hospital", items));
            l.Add(getTL("Lisburn Rd, City Hospital", "Bradbury Place, Bus stop", items));
            l.Add(getTL("Balmoral, Finnis Drive", "Lisburn Rd, Kings Hall", items));
            l.Add(getTL("Finaghy, Crossroads Lisburn Rd", "Balmoral, Finnis Drive", items));
            l.Add(getTL("Ladybrook, Turning Circle", "Andersonstown, Slievegallion Drive", items));
            l.Add(getTL("Andersonstown, Slievegallion Drive", "Kennedy Cen, Falls Road", items));
            l.Add(getTL("Kennedy Cen, Falls Road", "Falls Road, City Cemetery", items));
            l.Add(getTL("Falls Road, City Cemetery", "Falls Road, Royal Hospitals", items));
            l.Add(getTL("Falls Road, Royal Hospitals", "Belfast, Wellington Place", items));
            l.Add(getTL("Belfast, Queen Street", "Falls Road, Royal Hospitals", items));
            l.Add(getTL("Poleglass Est, Pembrooke Loop", "Brian's Well Road, Glenkeen", items));
            l.Add(getTL("Brian's Well Road, Glenkeen", "Belsteele Road, Glenwood", items));
            l.Add(getTL("Belsteele Road, Glenwood", "Suffolk Road, Glengoland Roundabout", items));
            l.Add(getTL("Suffolk Road, Glengoland Roundabout", "Suffolk Road, Woodbourne", items));
            l.Add(getTL("Suffolk Road, Woodbourne", "Glen Road, Glencolin", items));
            l.Add(getTL("Glen Road, Glencolin", "Shaws Road, Lenadoon Avenue", items));
            l.Add(getTL("Shaws Road, Lenadoon Avenue", "Andersonstown, Slievegallion Drive", items));
            l.Add(getTL("Suffolk Road, Glengoland Roundabout", "Poleglass Est, Pembrooke Loop", items));
            l.Add(getTL("Suffolk Road, Glengoland Roundabout", "Stewartstown Rd, Woodbourne", items));
            l.Add(getTL("Stewartstown Rd, Woodbourne", "Stewartstown Rd, Suffolk Library", items));
            l.Add(getTL("Stewartstown Rd, Suffolk Library", "Andersonstown, Slievegallion Drive", items));
            l.Add(getTL("Lagmore, Mount Eagles", "Lagmore, Lagmore Dale", items));
            l.Add(getTL("Lagmore, Lagmore Dale", "Twinbrook Est, St Mark's School", items));
            l.Add(getTL("Twinbrook Est, St Mark's School", "Upper Dunmurry Road, Cherry Road", items));
            l.Add(getTL("Upper Dunmurry Road, Cherry Road", "Suffolk Road, Glengoland Roundabout", items));
            l.Add(getTL("Upper Dunmurry Road, Cherry Road", "Twinbrook Est, Stewartstown Rd", items));
            l.Add(getTL("Twinbrook Est, Stewartstown Rd", "Lagmore, Lagmore Dale", items));
            l.Add(getTL("Glen Road, Glencolin", "Glen Road, St Teresa's", items));
            l.Add(getTL("Glen Road, St Teresa's", "Falls Road, City Cemetery", items));
            l.Add(getTL("Silverstream, Ballysillan Pk", "Crumlin Rd, Glenbank Corner", items));
            l.Add(getTL("Crumlin Rd, Glenbank Corner", "Ardoyne, Shops", items));
            l.Add(getTL("Ardoyne, Shops", "Woodvale Park, Bus stop", items));
            l.Add(getTL("Woodvale Park, Bus stop", "Shankill Road, Co-op", items));
            l.Add(getTL("Shankill Road, Co-op", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("Belfast, Chichester Street", "Shankill Road, Co-op", items));
            l.Add(getTL("Springmartin, Bus stop", "Ballygomartin, Glencairn Cres", items));
            l.Add(getTL("Ballygomartin, Glencairn Cres", "Woodvale Park, Bus stop", items));
            l.Add(getTL("Glencairn, Forthriver Road", "Ballygomartin, Glencairn Cres", items));
            l.Add(getTL("Springmartin, Bus stop", "Glencairn, Forthriver Road", items));
            l.Add(getTL("Carrs Glen, Joanmount", "Cliftonville Circus, Old Park Road", items));
            l.Add(getTL("Cliftonville Circus, Old Park Road", "Cliftonville Road, Academy", items));
            l.Add(getTL("Cliftonville Road, Academy", "Carlisle Circus, Antrim Road", items));
            l.Add(getTL("Belfast, Donegall Sq North", "Carlisle Circus, Antrim Road", items));
            l.Add(getTL("Cliftonville Circus, Old Park Road", "Crumlin Rd, Agnes Street", items));
            l.Add(getTL("Crumlin Rd, Agnes Street", "Carlisle Circus, Mater Hospital", items));
            l.Add(getTL("Carlisle Circus, Mater Hospital", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("Belfast, Donegall Sq North", "Carlisle Circus, Mater Hospital", items));
            l.Add(getTL("Ligoniel, Mountainhill", "Crumlin Rd, Glenbank Corner", items));
            l.Add(getTL("Crumlin Rd, Glenbank Corner", "Carrs Glen, Joanmount", items));
            l.Add(getTL("Sandyknowes, Ballyhenry Road", "Prince Charles Way, Glebe Rd", items));
            l.Add(getTL("Prince Charles Way, Glebe Rd", "Carnmoney, Carnvue", items));
            l.Add(getTL("Fairview Rd, Beverley Shops", "Fairview Rd, Ballyduff Shops", items));
            l.Add(getTL("Fairview Rd, Ballyduff Shops", "Ballyfore Road, Doagh Road", items));
            l.Add(getTL("Ballyfore Road, Doagh Road", "Doagh Road, Cherrylands", items));
            l.Add(getTL("Doagh Road, Green End", "Belfast, Upper Queen Street", items));
            l.Add(getTL("Belfast, Upper Queen Street", "Sandyknowes, Ballyhenry Road", items));
            l.Add(getTL("Doagh Road, Cherrylands", "Doagh Road, King's Road", items));
            l.Add(getTL("Doagh Road, King's Road", "Cloughfern, Whiteabbey Hospl", items));
            l.Add(getTL("Doagh Road, Cherrylands", "Cloughfern, Station Road", items));
            l.Add(getTL("Cloughfern, Station Road", "Northern Regional College, FHE", items));
            l.Add(getTL("Northern Regional College, FHE", "Belfast, Upper Queen Street", items));
            l.Add(getTL("Doagh Road, Cherrylands", "Glenville, Monkstown Avenue", items));
            l.Add(getTL("Hydepark, Trench Road", "Sandyknowes, Ballyhenry Road", items));
            l.Add(getTL("Braniel, Farmhurst Green", "Gilnahirk Road, Kingsway Park", items));
            l.Add(getTL("Gilnahirk Road, Kingsway Park", "Kings Road, Barnetts Rd", items));
            l.Add(getTL("Kings Road, Barnetts Rd", "Clarawood Park, Bus stop", items));
            l.Add(getTL("Clarawood Park, Bus stop", "Ballyhackamore, Village", items));
            l.Add(getTL("Ballyhackamore, Village", "Bloomfield Road, Roundabout", items));
            l.Add(getTL("Bloomfield Road, Roundabout", "Short Strand, Albertbridge Rd", items));
            l.Add(getTL("Dundonald, Ulster Hospital", "East Link Road, Comber Road", items));
            l.Add(getTL("East Link Road, Comber Road", "Dundonald, Ice Bowl", items));
            l.Add(getTL("Dundonald, Ice Bowl", "Tullycarnett, Leven Drive", items));
            l.Add(getTL("Tullycarnett, Leven Drive", "Kings Road, Barnetts Rd", items));
            l.Add(getTL("Kings Road, Barnetts Rd", "Upper Newtownards Rd, Knock Road", items));
            l.Add(getTL("Upper Newtownards Rd, Rosepark", "Massey Avenue, Castle Hill", items));
            l.Add(getTL("Massey Avenue, Castle Hill", "Belmont Rd, Gelston's Corner", items));
            l.Add(getTL("Belmont Rd, Gelston's Corner", "Connswater, Newtownards Rd", items));
            l.Add(getTL("Massey Avenue, Castle Hill", "Stormont, Massey Ave Gates", items));
            l.Add(getTL("Stormont, Massey Ave Gates", "Stormont, Castle Buildings", items));
            l.Add(getTL("Stormont, Castle Buildings", "Dundonald, Ulster Hospital", items));
            l.Add(getTL("Stormont, Dundonald House", "Stormont, Castle Buildings", items));
            l.Add(getTL("Holywood Exchange, Ikea", "Holywood Exchange, Sainsburys", items));
            l.Add(getTL("Holywood Exchange, Sainsburys", "Airport Road West, Heron Road", items));
            l.Add(getTL("Airport Road West, Heron Road", "Shorts, Main Office", items));
            l.Add(getTL("Shorts, Main Office", "Queens Road, Science Park", items));
            l.Add(getTL("Queens Road, Science Park", "Titanic Quarter, BMC", items));
            l.Add(getTL("Titanic Quarter, BMC", "Odyssey, Complex", items));
            l.Add(getTL("Odyssey, Complex", "Belfast, City Hall", items));
            l.Add(getTL("Belfast, Wellington Place", "Belfast, Queens Square Albert Clock", items));
            l.Add(getTL("Belfast, Queens Square Albert Clock", "Odyssey, Complex", items));
            l.Add(getTL("Shorts, Main Office", "Odyssey, Complex", items));
            l.Add(getTL("Holywood Exchange, Sainsburys", "Garnerville Road, Glenluce", items));
            l.Add(getTL("Garnerville Road, Glenluce", "Old Holywood Road, Kennelbridge", items));
            l.Add(getTL("Old Holywood Road, Kennelbridge", "Circular Road, CIYMS Grounds", items));
            l.Add(getTL("Circular Road, CIYMS Grounds", "Holywood Rd, Park Avenue", items));
            l.Add(getTL("Holywood Rd, Park Avenue", "Connswater, Newtownards Rd", items));
            l.Add(getTL("Old Holywood Road, Kennelbridge", "Holywood Rd, Knocknagoney Ave", items));
            l.Add(getTL("Holywood Rd, Knocknagoney Ave", "Holywood Exchange, Sainsburys", items));
            l.Add(getTL("Holywood Exchange, Sainsburys", "Redburn, Firmount Crescent", items));
            l.Add(getTL("Redburn, Firmount Crescent", "Holywood Rd, Knocknagoney Ave", items));
            l.Add(getTL("Holywood Rd, Knocknagoney Ave", "Holywood Rd, Tillysburn Park", items));
            l.Add(getTL("Holywood Rd, Tillysburn Park", "Holywood Rd, Park Avenue", items));
            l.Add(getTL("Holywood Rd, Tillysburn Park", "Garnerville Road, Glenluce", items));
            l.Add(getTL("Garnerville Road, Glenluce", "Redburn, Firmount Crescent", items));
            l.Add(getTL("Dundonald, Ice Bowl", "Kings Road, Sperrin Park", items));
            l.Add(getTL("Kings Road, Sperrin Park", "Gilnahirk Road, Kingsway Park", items));
            l.Add(getTL("Castlereagh Rd, Clonduff", "Montgomery Rd, Stirling Ave", items));
            l.Add(getTL("Montgomery Rd, Stirling Ave", "Mount Merrion Ave, Bell's Bridge", items));
            l.Add(getTL("Mount Merrion Ave, Bell's Bridge", "Mount Merrion, Rosetta Rd", items));
            l.Add(getTL("Rosetta, Knockbreda Road", "Forestside, Upper Galwally", items));
            l.Add(getTL("Forestside, Upper Galwally", "Annadale, Wellington Square", items));
            l.Add(getTL("Annadale, Wellington Square", "Ormeau Road, Agincourt Avenue", items));
            l.Add(getTL("Braniel, Farmhurst Green", "Kings Road, Sperrin Park", items));
            l.Add(getTL("Annadale, Wellington Square", "Rosetta, Knockbreda Road", items));
            l.Add(getTL("Rosetta, Knockbreda Road", "Rosetta, St John's Church", items));
            l.Add(getTL("Ormeau Road, Agincourt Avenue", "Ormeau Road, Cromac Place", items));
            l.Add(getTL("Ormeau Road, Cromac Place", "Belfast, Howard Street", items));
            l.Add(getTL("Rosetta Rd, Wynchurch Ave", "Upper Knockbreda Rd, Tudor Drive", items));
            l.Add(getTL("Upper Knockbreda Rd, Tudor Drive", "Castlereagh Rd, Clonduff", items));
            l.Add(getTL("Castlereagh Rd, Clonduff", "Ladas Drive, Castlereagh Road", items));
            l.Add(getTL("Ladas Drive, Castlereagh Road", "Mount Merrion Ave, Bell's Bridge", items));
            l.Add(getTL("Mount Merrion, Rosetta Rd", "Rosetta Rd, Wynchurch Ave", items));
            l.Add(getTL("Forestside, Upper Galwally", "Upper Knockbreda Rd, Tudor Drive", items));
            l.Add(getTL("Castlereagh Rd, Ladas Drive", "Short Strand, Albertbridge Rd", items));
            l.Add(getTL("Belfast, Chichester Street", "Carlisle Circus, Mater Hospital", items));
            l.Add(getTL("Crumlin Rd, Agnes Street", "Ardoyne, Shops", items));
            l.Add(getTL("Crumlin Rd, Glenbank Corner", "Ligoniel, Wolfhill", items));
            l.Add(getTL("Ligoniel, Wolfhill", "Ligoniel, Mountainhill", items));
            l.Add(getTL("Carrs Glen, Joanmount", "Cavehill Road, Westland Rd", items));
            l.Add(getTL("Cavehill Road, Westland Rd", "Limestone Road, Antrim Road", items));
            l.Add(getTL("Limestone Road, Antrim Road", "Yorkgate, Brougham Street", items));
            l.Add(getTL("Yorkgate, Brougham Street", "Corporation St, Clarendon Dock", items));
            l.Add(getTL("Corporation St, Clarendon Dock", "Belfast, Wellington Place", items));
            l.Add(getTL("Belfast, Queen Street", "Corporation St, Clarendon Dock", items));
            l.Add(getTL("Abbeycentre, Longwood Road", "Lower Whitewell, White City", items));
            l.Add(getTL("Shore Road, Gray's La", "Donegall Park Avenue, Downview Gdns", items));
            l.Add(getTL("Donegall Park Avenue, Downview Gdns", "Downview, Innisfayle Road", items));
            l.Add(getTL("Downview, Innisfayle Road", "Somerton Road, Hospice", items));
            l.Add(getTL("Somerton Road, Hospice", "Alexandra Park Ave, Bus Stop", items));
            l.Add(getTL("Alexandra Park Ave, Bus Stop", "Yorkgate, Brougham Street", items));
            l.Add(getTL("Carryduff, Church Road", "Cairnshill Road, Malvern Park", items));
            l.Add(getTL("Cairnshill Road, Malvern Park", "Newton Park, Colby Park", items));
            l.Add(getTL("Newton Park, Colby Park", "Newtownbreda, Tesco", items));
            l.Add(getTL("Newtownbreda, Tesco", "Beechill Road, Cedarhurst", items));
            l.Add(getTL("Beechill Road, Cedarhurst", "Purdysburn Road, Best's Hill", items));
            l.Add(getTL("Purdysburn Road, Best's Hill", "Hydebank, Milltown Road", items));
            l.Add(getTL("Hydebank, Milltown Road", "Belvoir Drive, Primary School", items));
            l.Add(getTL("Belvoir Drive, Primary School", "Forestside, Knockbreda Cemy", items));
            l.Add(getTL("Ormeau Road, Cromac Place", "Belfast, City Hall", items));
            l.Add(getTL("Belvoir Drive, Primary School", "Forestside, Upper Galwally", items));
            l.Add(getTL("Belfast, Wellington Place", "Ormeau Road, Cromac Place", items));
            l.Add(getTL("Forestside, Saintfield Rd", "Belvoir Drive, Primary School", items));
            l.Add(getTL("Newtownbreda, Tesco", "Newtownbreda Road, Greer Park Ave", items));
            l.Add(getTL("Newtownbreda Road, Greer Park Ave", "Hydebank, Milltown Road", items));
            l.Add(getTL("Rosetta, St John's Church", "Ravenhill Rd, Ormeau Rd", items));
            l.Add(getTL("Ravenhill Rd, Ormeau Rd", "Short Strand, Ravenhill Rd", items));
            l.Add(getTL("Short Strand, Ravenhill Rd", "Belfast, East Bridge St Central Stn", items));
            l.Add(getTL("Saintfield Rd, Mount Oriel", "Mount Merrion, Rosetta Rd", items));
            l.Add(getTL("Ravenhill Rd, Ormeau Rd", "Rosetta, Knockbreda Road", items));
            l.Add(getTL("Oldpark, Westland Road", "Cliftonville Circus, Alliance Ave", items));
            l.Add(getTL("Cliftonville Circus, Alliance Ave", "Ardoyne, Shops", items));
            l.Add(getTL("Ardoyne, Shops", "Ballygomartin, Glencairn Cres", items));
            l.Add(getTL("Ballygomartin, Glencairn Cres", "Springvale, West Circular Road", items));
            l.Add(getTL("Springvale, West Circular Road", "Royal Hospital, Grosvenor Rd", items));
            l.Add(getTL("Royal Hospital, Grosvenor Rd", "Belfast, Wellington Place", items));
            l.Add(getTL("Belfast, Queen Street", "Royal Hospital, Grosvenor Rd", items));
            l.Add(getTL("Belfast, Queen Street", "Castle Street, Castle Street", items));
            l.Add(getTL("Castle Street, Castle Street", "Royal Hospital, Grosvenor Rd", items));
            l.Add(getTL("Cliftonville Circus, Alliance Ave", "Carrs Glen, Joanmount", items));
            l.Add(getTL("Glen Road, St Teresa's", "Monagh Road, Bus stop", items));
            l.Add(getTL("Monagh Road, Bus stop", "Springvale, West Circular Road", items));
            l.Add(getTL("Brian's Well Road, Glenkeen", "Stewartstown Rd, Dairy Fm Ctr", items));
            l.Add(getTL("Stewartstown Rd, Dairy Fm Ctr", "Suffolk Road, Glengoland Roundabout", items));
            l.Add(getTL("Monagh Road, Bus stop", "Falls Road, St James", items));
            l.Add(getTL("Falls Road, St James", "Falls Road, Royal Hospitals", items));
            l.Add(getTL("Castle Street, Castle Street", "Falls Road, Royal Hospitals", items));
            l.Add(getTL("Belfast, Great Northern Mall", "Belfast, Albion Street", items));
            l.Add(getTL("Belfast, Albion Street", "Donegall Rd, Broadway", items));
            l.Add(getTL("Donegall Rd, Broadway", "Park Centre, Donegall Road", items));
            l.Add(getTL("Park Centre, Donegall Road", "Falls Road, City Cemetery", items));
            l.Add(getTL("Falls Road, City Cemetery", "Falls Park, Bus stop", items));
            l.Add(getTL("Kennedy Cen, Falls Road", "Falls Park, Bus stop", items));
            l.Add(getTL("Park Centre, Mall Entrance", "Tate's Avenue, Bus stop", items));
            l.Add(getTL("Tate's Avenue, Bus stop", "Belfast, Albion Street", items));
            l.Add(getTL("Donegall Rd, Broadway", "Park Centre, Mall Entrance", items));
            l.Add(getTL("Andersonstown, Slievegallion Drive", "Boucher Rd, Charles Hurst", items));
            l.Add(getTL("Boucher Rd, Charles Hurst", "Boucher Crescent, Retail Park", items));
            l.Add(getTL("Boucher Crescent, Retail Park", "Donegall Rd, Broadway", items));
            l.Add(getTL("Boucher Crescent, Retail Park", "Tate's Avenue, Bus stop", items));
            l.Add(getTL("Newforge Lane, Bus stop", "Malone Road, Cranmore Park", items));
            l.Add(getTL("Belfast, Donegall Sq East", "Bedford Street, Ulster Hall", items));
            l.Add(getTL("Bedford Street, Ulster Hall", "Bradbury Place, Bus stop", items));
            l.Add(getTL("Royal Hospital, Royal Hospitals", "Belfast, (Europa Buscentre)", items));
            l.Add(getTL("Belfast, (Europa Buscentre)", "Belfast, Donegall Sq East", items));
            l.Add(getTL("Royal Hospital, Royal Hospitals", "Belfast, Donegall Sq East", items));
            l.Add(getTL("Belfast, Upper Queen Street", "High Street, Skipper Street", items));
            l.Add(getTL("High Street, Skipper Street", "Duncrue Street, Ulsterbus", items));
            l.Add(getTL("Duncrue Street, Ulsterbus", "Dargan Crescent, Bus stop", items));
            l.Add(getTL("Dargan Crescent, Bus stop", "Westbank Road, Stena Line", items));
            l.Add(getTL("Westbank Road, Stena Line", "Duncrue Road, Cleansing Depot", items));
            l.Add(getTL("Duncrue Road, Cleansing Depot", "Duncrue Street, Ulsterbus", items));
            l.Add(getTL("Duncrue Street, Ulsterbus", "Royal Avenue, Castle Court", items));
            l.Add(getTL("Royal Avenue, Castle Court", "Belfast, Donegall Pl Boots", items));
            l.Add(getTL("George Best Airport, Belfast", "Belfast, Oxford Street", items));
            l.Add(getTL("Belfast, Oxford Street", "Belfast, Donegall Sq South", items));
            l.Add(getTL("Belfast, Donegall Sq South", "Belfast, (Europa Buscentre)", items));
            l.Add(getTL("Belfast, (Europa Buscentre)", "Belfast, Wellington Place", items));
            l.Add(getTL("Belfast, Queens Square Albert Clock", "George Best Airport, Belfast", items));
            l.Add(getTL("Odyssey, Complex", "George Best Airport, Belfast", items));
            l.Add(getTL("Odyssey, Complex", "Belfast, Oxford Street", items));
            l.Add(getTL("Titanic Quarter, BMC", "George Best Airport, Belfast", items));
            l.Add(getTL("Blacks Road Pk+R, Park and Ride", "Belfast, (Europa Buscentre)", items));
            l.Add(getTL("Blacks Road Pk+R, Park and Ride", "Blacks Road Pk+R, Park and Ride", items));
            l.Add(getTL("Connswater, Shopping Centre", "Mount Merrion Ave, Bell's Bridge", items));
            l.Add(getTL("Mount Merrion Ave, Bell's Bridge", "Rosetta Rd, Wynchurch Ave", items));
            l.Add(getTL("Rosetta Rd, Wynchurch Ave", "Cregagh Road, Hamel Drive", items));
            l.Add(getTL("Cregagh Road, Hamel Drive", "Clonduff Drive, Bus stop", items));
            l.Add(getTL("Clonduff Drive, Bus stop", "Roseberry Road, Bus stop", items));
            l.Add(getTL("Roseberry Road, Bus stop", "Connswater, Shopping Centre", items));
            l.Add(getTL("Clonduff Drive, Bus stop", "Montgomery Rd, Bus stop", items));
            l.Add(getTL("Connswater, Shopping Centre", "Holywood Rd, Arches Heatlh Centre", items));
            l.Add(getTL("Holywood Rd, Arches Heatlh Centre", "Clarawood Park, Bus stop", items));
            l.Add(getTL("Clarawood Park, Bus stop", "Clarawood Road, Bus stop", items));
            l.Add(getTL("Connswater, Shopping Centre", "Castlereagh Rd, Grand Parade", items));
            l.Add(getTL("Castlereagh Rd, Grand Parade", "Kings Road, Gilnahirk Rd", items));
            l.Add(getTL("Kings Road, Gilnahirk Rd", "Ardcarn Drive, Bus Stop", items));
            l.Add(getTL("Ardcarn Drive, Bus Stop", "Holywood Rd, Arches Heatlh Centre", items));
            l.Add(getTL("Connswater, Shopping Centre", "Knocknagoney, Tesco", items));
            l.Add(getTL("Knocknagoney, Tesco", "Knocknagoney, Tesco", items));
            l.Add(getTL("Knocknagoney, Tesco", "Holywood Rd, Arches Heatlh Centre", items));
            l.Add(getTL("Belvoir Drive, Bus Stop", "Forestside, Sainsbury", items));
            l.Add(getTL("Forestside, Sainsbury", "Woodbreda Park, Bus stop", items));
            l.Add(getTL("Woodbreda Park, Bus stop", "Belvoir Drive, Castlecoole Pk", items));
            l.Add(getTL("Belvoir Drive, Castlecoole Pk", "Dunseverick Ave, Drumart Dr", items));
            l.Add(getTL("Dunseverick Ave, Drumart Dr", "Belvoir Drive, Bus Stop", items));
            l.Add(getTL("Forestside, Sainsbury", "Elgin Street, Dunnes Stores", items));
            l.Add(getTL("Elgin Street, Dunnes Stores", "Raphael Street, Bus stop", items));
            l.Add(getTL("Raphael Street, Bus stop", "Belfast, Adelaide St", items));
            l.Add(getTL("Belfast, Adelaide St", "Elgin Street, Dunnes Stores", items));
            l.Add(getTL("Forestside, Sainsbury", "Wynchurch Avenue, Bus stop", items));
            l.Add(getTL("Wynchurch Avenue, Bus stop", "Annadale Embkmnt, Annadale Cr", items));
            l.Add(getTL("Annadale Embkmnt, Annadale Cr", "Elgin Street, Dunnes Stores", items));
            l.Add(getTL("Annadale Embkmnt, Annadale Cr", "Forestside, Sainsbury", items));
            l.Add(getTL("Abbeycentre, Shore entrance (Dunnes)", "Rathcoole, Rathcoole Drive", items));
            l.Add(getTL("Rathcoole, Rathcoole Drive", "Owenreagh Drive, Bus stop", items));
            l.Add(getTL("Owenreagh Drive, Bus stop", "Rosslea Way, Bus stop", items));
            l.Add(getTL("Rosslea Way, Bus stop", "Tesco, Abbey Retail Park Church Road", items));
            l.Add(getTL("Tesco, Abbey Retail Park Church Road", "Abbeycentre, Shore entrance (Dunnes)", items));
            l.Add(getTL("Abbeycentre, Shore entrance (Dunnes)", "Castle Avenue, Bus stop", items));
            l.Add(getTL("Castle Avenue, Bus stop", "Shore Road, Mount Vernon Rd", items));
            l.Add(getTL("Shore Road, Mount Vernon Rd", "Gunnell Hill, Bus stop", items));
            l.Add(getTL("Gunnell Hill, Bus stop", "Tesco, Abbey Retail Park Church Road", items));
            l.Add(getTL("Abbeycentre, Shore entrance (Dunnes)", "Doagh Road, Abbots Cross", items));
            l.Add(getTL("Doagh Road, Abbots Cross", "Fernagh Road, Bus stop", items));
            l.Add(getTL("Fernagh Road, Bus stop", "Tuleevin Drive, Bus stop", items));
            l.Add(getTL("Tuleevin Drive, Bus stop", "Abbots Cross, Post Office", items));
            l.Add(getTL("Abbots Cross, Post Office", "Tesco, Abbey Retail Park Church Road", items));
            l.Add(getTL("Abbeycentre, Shore entrance (Dunnes)", "Carnmoney, Cemetery", items));
            l.Add(getTL("Carnmoney, Cemetery", "Fairview Rd, Beverley Shops", items));
            l.Add(getTL("Carnmoney, Cemetery", "Tesco, Abbey Retail Park Church Road", items));

            return l;
        }

        private LocationPair getTL(string name, string name2, Dictionary<string, int> items)
        {
            int int1 = items[name];
            int int2 = items[name2];
            return new LocationPair(int1, int2);
        }
    }
}
